### ISSUE TITLE
ELO loss on shakmaty upgrade

### ISSUE THREAD

**Issue by ianagbip1oti** [niklasf/shakmaty#64] opened 2023-01-06 16:33 UTC
Hi, I made a change to my engine, which is just a shakmaty upgrade https://github.com/princesslana/princhess/pull/155

But on running an sprt test with cutechess, I get the following results:
```
princhess-sprt_equal-1  | Score of princhess vs princhess-main: 918 - 1069 - 623  [0.471] 2610
princhess-sprt_equal-1  | ...      princhess playing White: 461 - 541 - 303  [0.469] 1305
princhess-sprt_equal-1  | ...      princhess playing Black: 457 - 528 - 320  [0.473] 1305
princhess-sprt_equal-1  | ...      White vs Black: 989 - 998 - 623  [0.498] 2610
princhess-sprt_equal-1  | Elo difference: -20.1 +/- 11.6, LOS: 0.0 %, DrawRatio: 23.9 %
princhess-sprt_equal-1  | SPRT: llr -2.95 (-100.3%), lbound -2.94, ubound 2.94 - H0 was accepted
```

Any ideas on what could cause this elo loss?

The likely critical parts called on every rollout are:
This loop through Board#occupied: https://github.com/princesslana/princhess/blob/main/src/state.rs#L199-L216
Make move: https://github.com/princesslana/princhess/blob/main/src/state.rs#L108-L124
Evaluation, including a syzygy lookup with shakmaty-syzygy: https://github.com/princesslana/princhess/blob/main/src/evaluation.rs#L16-L32

**Comment by niklasf** [comment] 2023-01-07 20:21
Hi, thanks for reporting!

For reference:
```diff
-shakmaty = "=0.20.1"
+shakmaty = "=0.23.0"
```

To narrow things down, could you please repeat the test without using tablebases?

**Comment by ianagbip1oti** [comment] 2023-01-07 22:16
Will do.

I actually tried to just do an upgrade on once_cell, but that, by itself, was dropping some elo, which I really didn't expect. So, I'll let you know as I run more tests.

**Comment by ianagbip1oti** [comment] 2023-01-11 21:13
Managed to separate out the once_cell change.
```
princhess-sprt_equal-1  | Score of princhess vs princhess-main: 644 - 773 - 723  [0.470] 2140
princhess-sprt_equal-1  | ...      princhess playing White: 311 - 402 - 357  [0.457] 1070
princhess-sprt_equal-1  | ...      princhess playing Black: 333 - 371 - 366  [0.482] 1070
princhess-sprt_equal-1  | ...      White vs Black: 682 - 735 - 723  [0.488] 2140
princhess-sprt_equal-1  | Elo difference: -21.0 +/- 12.0, LOS: 0.0 %, DrawRatio: 33.8 %
princhess-sprt_equal-1  | SPRT: llr -2.96 (-100.5%), lbound -2.94, ubound 2.94 - H0 was accepted
```

Running a test without use tablebases next

**Comment by ianagbip1oti** [comment] 2023-01-14 06:08
Without tablebases
```
princhess-sprt_equal-1  | Score of princhess vs princhess-main: 1132 - 1097 - 1033  [0.505] 3262
princhess-sprt_equal-1  | ...      princhess playing White: 577 - 526 - 528  [0.516] 1631
princhess-sprt_equal-1  | ...      princhess playing Black: 555 - 571 - 505  [0.495] 1631
princhess-sprt_equal-1  | ...      White vs Black: 1148 - 1081 - 1033  [0.510] 3262
princhess-sprt_equal-1  | Elo difference: 3.7 +/- 9.8, LOS: 77.1 %, DrawRatio: 31.7 %
princhess-sprt_equal-1  | SPRT: llr 2.96 (100.5%), lbound -2.94, ubound 2.94 - H1 was accepted
```

**Comment by niklasf** [comment] 2023-01-15 09:33
Is this shakmaty 0.20.1 without tablebases vs shakmaty 0.23.0 without tablebases?

**Comment by ianagbip1oti** [comment] 2023-01-15 11:59
Yes, both without tablebases.

**Comment by niklasf** [comment] 2023-01-15 12:18
Do I understand correctly, that SPRT found a small but significant performance regression? Might be worth bisecting further. In particular:

* [v0.20.4](https://github.com/niklasf/shakmaty/blob/master/CHANGELOG.md#v0204) includes a rewrite of pawn move generation
* [v0.23.0](https://github.com/niklasf/shakmaty/blob/master/CHANGELOG.md#v0230) changed Zobrist hashing.

**Comment by ianagbip1oti** [comment] 2023-01-15 15:09
The first sprt used tablebases and did find a small by significant performance regression, I use bounds -10,-2.5.

The second sprt did not use tablebases and found there was no regression.

Would this suggest the issue is more likely in a shakmaty-syzygy change?

I can perform more incremental updates to see how things change

**Comment by niklasf** [comment] 2023-01-15 15:20
Barely anything happened in the relevant range of shakmaty-syzygy versions. Notable maybe:
* `ProbeError::CorruptedTable` is now larger in order to carry a backtrace. 
* Followed dependencies, including `once_cell`, which is used for every table.

**Comment by ianagbip1oti** [comment] 2023-01-15 16:06
Updating once_cell for me caused a performance drop, but I didn't figure out why. I made a change to use it less before I upgraded it.

**Comment by ianagbip1oti** [comment] 2023-01-17 13:39
Upgrading shakmaty to 0.20.7 was good.

Upgrading from 0.20.7 to 0.21.4 was a small elo loss, so I tried just to 0.20.0, and this also suffered a small elo loss


So for shakmaty from 0.20.7 -> 0.21.0 and skakmaty-syzygy from 0.18.0 -> 0.19.0:
```
princhess-sprt_equal-1  | Score of princhess vs princhess-main: 822 - 963 - 804  [0.473] 2589
princhess-sprt_equal-1  | ...      princhess playing White: 418 - 480 - 396  [0.476] 1294
princhess-sprt_equal-1  | ...      princhess playing Black: 404 - 483 - 408  [0.469] 1295
princhess-sprt_equal-1  | ...      White vs Black: 901 - 884 - 804  [0.503] 2589
princhess-sprt_equal-1  | Elo difference: -18.9 +/- 11.1, LOS: 0.0 %, DrawRatio: 31.1 %
princhess-sprt_equal-1  | SPRT: llr -2.96 (-100.6%), lbound -2.94, ubound 2.94 - H0 was accepted
```

**Comment by niklasf** [comment] 2023-01-20 19:36
Looks like

> Implement `IntoIterator` for `Board`, replacing `Board::pieces().`

is a good candidate for the bad change, because it's used internally for Zobrist hashing. So far there was no benchmark for Zobrist hashing, but retroactively adding one, I do see a regression there.

Optimized via 71521853a1d3dd62c751a6c99002b74050d3dff7, pushed to master branch:

```
bench_zobrist_hash
  Instructions:                 778 (-66.87952%)
  L1 Accesses:                 1072 (-64.44444%)
  L2 Accesses:                   15 (+7.142857%)
  RAM Accesses:                  58 (-17.14286%)
  Estimated Cycles:            3177 (-42.60163%)
```

Could you please run another test, to see what if anything these gains translate to, and if this explains part of all of the ELO loss?

**Comment by ianagbip1oti** [comment] 2023-01-21 12:24
With: https://github.com/princesslana/princhess/pull/155
```
princhess-sprt_equal-1  | Score of princhess vs princhess-main: 725 - 860 - 724  [0.471] 2309
princhess-sprt_equal-1  | ...      princhess playing White: 351 - 433 - 370  [0.464] 1154
princhess-sprt_equal-1  | ...      princhess playing Black: 374 - 427 - 354  [0.477] 1155
princhess-sprt_equal-1  | ...      White vs Black: 778 - 807 - 724  [0.494] 2309
princhess-sprt_equal-1  | Elo difference: -20.3 +/- 11.7, LOS: 0.0 %, DrawRatio: 31.4 %
princhess-sprt_equal-1  | SPRT: llr -2.95 (-100.0%), lbound -2.94, ubound 2.94 - H0 was accepted
```

Unexpected. Your change should be good. I moved away from board.clone() us well. Maybe I don't get the benefit 'cos I'm doing some incremental hashing?

**Comment by ianagbip1oti** [comment] 2023-10-12 06:09
I switched to using fathom for tablebases and upgraded shakmaty to 0.26. I was able to do this without elo loss (somewhere between 0 and +20 elo). As such I won't be looking at anything on this ticket anymore.

**Comment by niklasf** [comment] 2023-10-15 15:23
Thanks for the update. I'll close the issue, in that case.

**Closed by niklasf** 2023-10-15 15:23 UTC
